# Generated by Django 4.2.7 on 2025-10-22 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скважины')),
                ('area', models.CharField(max_length=255, verbose_name='Участок')),
                ('structure', models.CharField(max_length=255, verbose_name='Сооружение')),
                ('design_depth', models.FloatField(verbose_name='Проектная глубина')),
                ('offline_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending')], default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wells',
            },
        ),
    ]
