# Generated by Django 4.2.7 on 2025-10-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drilling_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.FloatField(verbose_name='Глубина от (м)')),
                ('depth_to', models.FloatField(verbose_name='Глубина до (м)')),
                ('thickness', models.FloatField(editable=False, verbose_name='Мощность (м)')),
                ('lithology', models.CharField(choices=[('prs', 'ПРС'), ('peat', 'Торф'), ('loam', 'Суглинок'), ('sandy_loam', 'Супесь'), ('sand', 'Песок')], max_length=20, verbose_name='Литология')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('offline_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending')], default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='drilling_log.well')),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['depth_from'],
            },
        ),
    ]
